### ISSUE TITLE
【数据源无法展示】数据源是不是无法展示， master分支的sql，执行后core_datasource的null，前台无法添加datasource哦。感谢

### ISSUE THREAD

**Issue by arraycto** [Hardork/hwqbi-backend#3]
【数据源无法展示】数据源是不是无法展示， master分支的sql，执行后core_datasource的null，前台无法添加datasource哦。感谢

![image](https://github.com/user-attachments/assets/7a3c73f7-725b-4a16-9311-840807181791)

**Comment by Hardork** [comment]
感谢你提交的issue，这个问题是由于功能未完善的原因，很快就会得到解决🙏
